name: odo24_mobile
description: ODO24 Mobile
publish_to: 'none'

version: 3.0.0+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.0
  package_info_plus: ^8.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/logo_dark.svg
